### ISSUE TITLE
实测效果没有paper中展示的好

### ISSUE THREAD

**Issue by rwywenyi** [ali-vilab/FlashFace#11]
1、实测效果没有paper中展示的好，人脸一致性很差，请问是sd1.5的问题吗？
2、看算法架构，reference net和sd是分离的，给的模型权重只有一个接近10G的flashface.ckpt，这是集成两个model了嘛？

**Comment by jshilong** [comment]
> 1、实测效果没有paper中展示的好，人脸一致性很差，请问是sd1.5的问题吗？ 2、看算法架构，reference net和sd是分离的，给的模型权重只有一个接近10G的flashface.ckpt，这是集成两个model了嘛？

1. paper中展示的结果是给定了 face position的，效果会更稳定一些，并且都是四张ref图生成的（我们在论文提到了），可以提供下您的具体例子？
2. 是的，集成了两个model

**Comment by rwywenyi** [comment]
> > 1、实测效果没有paper中展示的好，人脸一致性很差，请问是sd1.5的问题吗？ 2、看算法架构，reference net和sd是分离的，给的模型权重只有一个接近10G的flashface.ckpt，这是集成两个model了嘛？
> 
> 可以把您的 ref 图 与 prompt放在这里，我来测试一下
![flashface和instantid对比](https://github.com/ali-vilab/FlashFace/assets/136083041/7a5f2c4c-2483-4eea-9555-b7680da2565e)
<img width="402" alt="肖战" src="https://github.com/ali-vilab/FlashFace/assets/136083041/548223a1-1095-489b-848a-9a438c784baf">

**Comment by rwywenyi** [comment]
> > 1、实测效果没有paper中展示的好，人脸一致性很差，请问是sd1.5的问题吗？ 2、看算法架构，reference net和sd是分离的，给的模型权重只有一个接近10G的flashface.ckpt，这是集成两个model了嘛？
> 
> 1. paper 中展示的结果使用的 ckpt 与我们 release 的训练 setting 不太一样，但是效果应该是差不多的（不过 release 版本训练时间更久，变为艺术品的能力应该变差了），另一方面是 paper 的生成图给定了 face position的，效果会更稳定一些，因为随机生成有时可能会产生很小的脸，受sd1.5分辨率所限，相似度就会出问题，另一方面，paper中真人图像基本是四张ref图生成的（我们在论文提到了，并在补充材料展示了使用的四张 ref 图），
> 
> 可以提供下您的具体例子，我来帮忙找找原因，我测试下来复杂prompt整体图片受限于sd1.5有时候会崩，但是人脸相似度不应该有问题, readme 与 gif 中的例子都是这次 release 的模型跑的
> 
> 2. 是的，集成了两个model

请问可以只提供reference net权重吗，这样可以测试其他sd1.5模型的效果

**Comment by jshilong** [comment]
仅仅 a man 对于 flashface 来说指引太过模糊了，这个情况下instantid有ref图关键点指引，所以它依旧能稳定出图，公平条件下可以对flashface 提供一个face_bbox =[0.3, 0.1, 0.6, 0.4] 作为指引，可以使用我的ipynotebook复现以下结果

```
face_imgs = [Image.open(f"ref.png").convert("RGB")]
need_detect = True
pos_prompt = "A young  man "
neg_prompt = "beard"
# No face position
face_bbox =[0.3, 0.1, 0.6, 0.4] 
#face_bbox =[0., 0., 0., 0.] 
# bigger these three parameters leads to more fidelity but less diversity 
lamda_feat = 1.1
face_guidence = 2.5
step_to_launch_face_guidence = 600

steps = 35
default_text_control_scale = 7.5

default_seed = 0


imgs = generate(pos_prompt=pos_prompt, 
                    neg_prompt=neg_prompt, 
                    steps=steps, 
                    face_bbox=face_bbox,
                    lamda_feat=lamda_feat, 
                    face_guidence=face_guidence, 
                    num_sample=4, 
                    text_control_scale=default_text_control_scale, 
                    seed=default_seed, 
                    step_to_launch_face_guidence=step_to_launch_face_guidence, 
                    reference_faces=face_imgs,
                    need_detect=need_detect
                    )


# show the generated images
img_size = imgs[0].size


num_imgs = len(imgs)
save_img = Image.new('RGB', (img_size[0] * (num_imgs + 1), img_size[1]))
for i, img in enumerate(imgs):
    save_img.paste(img, ((i + 1) * img_size[0], 0))

# paste all four reference face imgs to the first

resize_w = img_size[0] // 2
resize_h = img_size[1] // 2

for id, ref_img in enumerate(face_imgs):
    # resize the ref_img keep the ratio to fit the size of (resize_w, resize_h)
    w_ratio = resize_w / ref_img.size[0]
    h_ratio = resize_h / ref_img.size[1]
    ratio = min(w_ratio, h_ratio)
    ref_img = ref_img.resize(
        (int(ref_img.size[0] * ratio), int(ref_img.size[1] * ratio)))

    if id < 2:
        save_img.paste(ref_img, (id * resize_w, 0))
    else:
        save_img.paste(ref_img, ((id - 2) * resize_w, resize_h))

display(save_img)
```
<img width="2139" alt="截屏2024-04-25 下午7 52 21" src="https://github.com/ali-vilab/FlashFace/assets/61961338/522c69e1-06c9-4c4b-9256-9faa626281cf">


当你的prompt 更具体一些，不给 face bbox 也可以出更多样的图

```
face_imgs = [Image.open(f"ref.png").convert("RGB")]
need_detect = True
pos_prompt = "A young  man in suit"
neg_prompt = "beard"
# No face position
#face_bbox =[0.2, 0.1, 0.5, 0.4] 
face_bbox =[0., 0., 0., 0.] 
# bigger these three parameters leads to more fidelity but less diversity 
lamda_feat = 1.1
face_guidence = 2.5
step_to_launch_face_guidence = 600

steps = 35
default_text_control_scale = 7.5

default_seed = 0


imgs = generate(pos_prompt=pos_prompt, 
                    neg_prompt=neg_prompt, 
                    steps=steps, 
                    face_bbox=face_bbox,
                    lamda_feat=lamda_feat, 
                    face_guidence=face_guidence, 
                    num_sample=4, 
                    text_control_scale=default_text_control_scale, 
                    seed=default_seed, 
                    step_to_launch_face_guidence=step_to_launch_face_guidence, 
                    reference_faces=face_imgs,
                    need_detect=need_detect
                    )


# show the generated images
img_size = imgs[0].size
num_imgs = len(imgs)
save_img = Image.new('RGB', (img_size[0] * (num_imgs + 1), img_size[1]))
for i, img in enumerate(imgs):
    save_img.paste(img, ((i + 1) * img_size[0], 0))

# paste all four reference face imgs to the first

resize_w = img_size[0] // 2
resize_h = img_size[1] // 2

for id, ref_img in enumerate(face_imgs):
    # resize the ref_img keep the ratio to fit the size of (resize_w, resize_h)
    w_ratio = resize_w / ref_img.size[0]
    h_ratio = resize_h / ref_img.size[1]
    ratio = min(w_ratio, h_ratio)
    ref_img = ref_img.resize(
        (int(ref_img.size[0] * ratio), int(ref_img.size[1] * ratio)))

    if id < 2:
        save_img.paste(ref_img, (id * resize_w, 0))
    else:
        save_img.paste(ref_img, ((id - 2) * resize_w, resize_h))

display(save_img)
```

<img width="2125" alt="截屏2024-04-25 下午7 46 02" src="https://github.com/ali-vilab/FlashFace/assets/61961338/3cc6e8e6-3d46-40cd-8c29-f484403176d6">





相比于instantid，因为instantid使用了关键点，虽然这保证了它在任意情况下的出图稳定性，但是也导致语言对脸部的控制能力变弱，它生成图跟 ref 图的位置 pose 表情几乎一样

Flashface 灵活性更高一些，即我们 paper 所说的受语言控制能力更强,即使只有一张ref图我们生成图也可以与 ref 图有较大的variance， 可以看到我们生成图与ref图在pose，表情方面是有varience的，不是照抄的ref图

另一方面，提供四张图更能体现我们算法的优势，生成图 varience 更大

**Comment by jshilong** [comment]
> > > 1、实测效果没有paper中展示的好，人脸一致性很差，请问是sd1.5的问题吗？ 2、看算法架构，reference net和sd是分离的，给的模型权重只有一个接近10G的flashface.ckpt，这是集成两个model了嘛？
> > 
> > 
> > 
> > 1. paper 中展示的结果使用的 ckpt 与我们 release 的训练 setting 不太一样，但是效果应该是差不多的（不过 release 版本训练时间更久，变为艺术品的能力应该变差了），另一方面是 paper 的生成图给定了 face position的，效果会更稳定一些，因为随机生成有时可能会产生很小的脸，受sd1.5分辨率所限，相似度就会出问题，另一方面，paper中真人图像基本是四张ref图生成的（我们在论文提到了，并在补充材料展示了使用的四张 ref 图），
> > 
> > 可以提供下您的具体例子，我来帮忙找找原因，我测试下来复杂prompt整体图片受限于sd1.5有时候会崩，但是人脸相似度不应该有问题, readme 与 gif 中的例子都是这次 release 的模型跑的
> > 
> > 2. 是的，集成了两个model
> 
> 请问可以只提供reference net权重吗，这样可以测试其他sd1.5模型的效果

我们这次 release的版本是全微调的，可能不能支持这样的操作

**Comment by rwywenyi** [comment]
好的，我明白了，非常感谢您的回复，从一开始就关注到这篇paper了，基本每隔几天就来看看是否开源，

**Comment by jshilong** [comment]
> 好的，我明白了，非常感谢您的回复，从一开始就关注到这篇paper了，基本每隔几天就来看看是否开源，

哈哈，感谢您的关注，我跑了三个例子，您看看现在效果令人满意吗

**Comment by jshilong** [comment]
> 好的，我明白了，非常感谢您的回复，从一开始就关注到这篇paper了，基本每隔几天就来看看是否开源，

您还有其他问题吗，如果没有，我今天就先把这个issue close了，有问题随时 issue提问讨论
